package io.github.joyen09.exchangecore.guard;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.github.joyen09.exchangecore.config.ExchangeProperties;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.net.URI;
import java.net.URL;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.api.DynamicTest;
import java.util.stream.Stream;
import org.springframework.core.env.MapPropertySource;
import org.springframework.core.env.StandardEnvironment;

/**
 * Guards the guard (ADR-0003).
 *
 * <p>The failure mode this test exists for is procedural, not logical: Phase 3 adds a market data
 * endpoint, Phase 4 adds a fills feed, and each new property arrives unguarded because whoever
 * added it did not think about the allowlist. A guard that enumerates property names cannot detect
 * that; so the guard covers the namespace, and this test proves the coverage holds for properties
 * that do not exist yet.
 *
 * <p>The per-property cases are generated by reflection over {@link ExchangeProperties}. Adding an
 * endpoint property there adds a test case for it automatically — including for whoever forgets.
 */
class GuardCoversEveryEndpointPropertyTest {

    private static final String MAINNET = "https://api.binance.com";

    private static final Map<String, Object> VALID_CONFIGURATION = Map.of(
            "exchange.rest-base-url", "https://testnet.binance.vision",
            "exchange.ws-base-url", "wss://stream.testnet.binance.vision:9443",
            "exchange.connect-timeout", "3s",
            "exchange.read-timeout", "10s");

    @TestFactory
    @DisplayName("every declared endpoint property is refused a mainnet value")
    Stream<DynamicTest> everyDeclaredEndpointPropertyIsGuarded() {
        Set<String> declared = declaredEndpointProperties();
        assertThat(declared)
                .as("reflection found no endpoint properties — the discovery below is broken, "
                        + "which would make every generated case vacuous")
                .contains("exchange.rest-base-url", "exchange.ws-base-url");

        return declared.stream()
                .map(property -> DynamicTest.dynamicTest(property, () -> assertGuardRejects(property, MAINNET)));
    }

    @Test
    @DisplayName("an endpoint property nobody has declared yet is guarded too")
    void undeclaredFutureEndpointPropertyIsGuarded() {
        // The Phase 3 / Phase 4 scenario, simulated: a property that exists in configuration but on
        // no @ConfigurationProperties class. Namespace coverage is what catches it.
        assertGuardRejects("exchange.market-data-url", MAINNET);
        assertGuardRejects("exchange.user-stream-endpoint", "wss://stream.binance.com:9443/ws");
    }

    @Test
    @DisplayName("a URL value is caught even when the property name does not read like one")
    void urlValueIsGuardedRegardlessOfPropertyName() {
        assertGuardRejects("exchange.fallback", MAINNET);
    }

    @Test
    @DisplayName("non-endpoint settings in the namespace are left alone")
    void nonEndpointPropertiesAreNotFlagged() {
        Map<String, Object> configuration = new HashMap<>(VALID_CONFIGURATION);
        configuration.put("exchange.max-retries", "5");
        configuration.put("exchange.recv-window", "5000");
        configuration.put("exchange.connect-timeout", "3s");

        assertThatCode(() -> runGuard(configuration))
                .as("a false positive here would make the guard something developers route around")
                .doesNotThrowAnyException();
    }

    @Test
    @DisplayName("the valid testnet configuration passes")
    void validConfigurationPasses() {
        assertThatCode(() -> runGuard(VALID_CONFIGURATION)).doesNotThrowAnyException();
    }

    @Test
    @DisplayName("a removed required endpoint fails loudly rather than disabling its own check")
    void removingARequiredEndpointFails() {
        Map<String, Object> configuration = new HashMap<>(VALID_CONFIGURATION);
        configuration.remove("exchange.ws-base-url");

        assertThatThrownBy(() -> runGuard(configuration))
                .isInstanceOf(ExchangeEndpointNotAllowedException.class)
                .hasMessageContaining("exchange.ws-base-url")
                .hasMessageContaining("missing or blank");
    }

    private static void assertGuardRejects(String property, String value) {
        Map<String, Object> configuration = new HashMap<>(VALID_CONFIGURATION);
        configuration.put(property, value);

        assertThatThrownBy(() -> runGuard(configuration))
                .as("property '%s' must be covered by the endpoint guard", property)
                .isInstanceOf(ExchangeEndpointNotAllowedException.class)
                .satisfies(failure -> assertThat(((ExchangeEndpointNotAllowedException) failure).getPropertyName())
                        .isEqualTo(property));
    }

    private static void runGuard(Map<String, Object> configuration) {
        StandardEnvironment environment = new StandardEnvironment();
        environment.getPropertySources().addFirst(new MapPropertySource("test-configuration", configuration));
        new ExchangeEndpointGuard().postProcessEnvironment(environment, null);
    }

    /**
     * Endpoint properties as declared by {@link ExchangeProperties}: a no-argument accessor
     * returning a string or URL type whose name reads like an endpoint.
     */
    private static Set<String> declaredEndpointProperties() {
        Set<String> names = new TreeSet<>();
        for (Method method : ExchangeProperties.class.getDeclaredMethods()) {
            if (method.getParameterCount() != 0 || !Modifier.isPublic(method.getModifiers())) {
                continue;
            }
            if (!method.getName().startsWith("get")) {
                continue;
            }
            Class<?> returnType = method.getReturnType();
            if (returnType != String.class && returnType != URI.class && returnType != URL.class) {
                continue;
            }
            String property = toKebabCase(method.getName().substring(3));
            if (readsLikeEndpoint(property)) {
                names.add("exchange." + property);
            }
        }
        return names;
    }

    private static String toKebabCase(String camelCase) {
        return camelCase.replaceAll("([a-z0-9])([A-Z])", "$1-$2").toLowerCase(Locale.ROOT);
    }

    private static boolean readsLikeEndpoint(String property) {
        String compact = property.replaceAll("[^a-z0-9]", "");
        return compact.endsWith("url") || compact.endsWith("uri") || compact.endsWith("endpoint");
    }
}
